name: Update copyright year(s) in license file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 1 *'
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
    update-license-year:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jmoney/gha-license-updater@main
              with:
                assignee: jmoney
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
